apiVersion: v1
kind: Service
metadata:
  name: {{ include "orloj.postgresFullname" . }}
  labels:
    {{- include "orloj.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "orloj.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
